version: '3.8'
services:
  db_demo:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: lenas
      POSTGRES_PASSWORD: 12345678
  demo
    container_name: demo
    command: java -jar epam-demo.jar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345678
      SPRING_PROFILE: prod
    depends_on:
      - demo
